services:
  postgres:
    image: postgres:16-alpine
    container_name: job_tracker_db
    environment:
      POSTGRES_DB: job_tracker_db
      POSTGRES_USER: job_user
      POSTGRES_PASSWORD: fr001009
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: